FROM node:20.10-alpine3.18

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install -g npm & npm install & npm install -g pm2

COPY . .
RUN npm run build
RUN chmod +x ./run_consumers.sh
USER node:node
CMD ["./run_consumers.sh"]