global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'product_api'
    static_configs:
      - targets: ['api:9464']
remote_write:
  - url: 'http://grafana:3000'
    basic_auth:
      username: 'admin'
      password: 'admin'